error_descr = {"S001": "Too long",
               "S002": "Indentation is not a multiple of four",
               "S003": "Unnecessary semicolon",
               "S004": "At least two spaces before inline comment required",
               "S005": "TODO found",
               "S006": "More than two blank lines used before this line",
               "S007": "Too many spaces after def or class",
               "S008": "Class name '-' should be written in CamelCase",
               "S009": "Function name '-' should be written in snake_case",
               "S010": "Argument name '-' should be written in snake_case",
               "S011": "Variable '-' should be written in snake_case",
               "S012": "The default argument value is mutable"}
